### ISSUE TITLE
Failed to download WSA

### ISSUE THREAD

**Issue by ma0shu** [pagkly/magiskonwaydroid#7]
**Error in Workflow/Waydroid?**
Workflow

**Describe the bug**
Failed to download WSA. Log below.

**Additional context**
`Run import requests
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f2d67036310>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='store.rg-adguard.net', port=443): Max retries exceeded with url: /api/GetFiles (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2d67036310>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/_temp/54c63fb9-e8e2-4427-915c-7f4ea21060a4.py", line 14, in <module>
    res = requests.post("https://store.rg-adguard.net/api/GetFiles", f"type=CategoryId&url=858014f3-3934-4abe-80[78](https://github.com/ma0shu/MagiskOnWaydroid/runs/7703756573?check_suite_focus=true#step:3:79)-4aa1[93](https://github.com/ma0shu/MagiskOnWaydroid/runs/7703756573?check_suite_focus=true#step:3:94)e74ca8&ring={release_type}&lang=en-US", headers={	
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='store.rg-adguard.net', port=443): Max retries exceeded with url: /api/GetFiles (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2d67036310>: Failed to establish a new connection: [Errno [111](https://github.com/ma0shu/MagiskOnWaydroid/runs/7703756573?check_suite_focus=true#step:3:112)] Connection refused'))
Error: Process completed with exit code 1.`

**Comment by TheBinger** [comment]
You can go to [rg-adguard](https://store.rg-adguard.net/) and get the url of WSA package, then edit workflow.yaml.

**Comment by BlurryFlurry** [comment]
Check out my forked repo.
I've created two patches and made two pull requests and made it work.
https://github.com/BlurryFlurry/MagiskOnWaydroid/actions/runs/2978087525
(You can also get the artifact)

The [first patch](https://github.com/pagkly/MagiskOnWaydroid/compare/main...BlurryFlurry:MagiskOnWaydroid:BlurryFlurry-patch-disable-cf-bypass?short_path=173145d#diff-173145d7ba39d4d25fd2fc4cc87fdc8ddc838bdfd5a278844b081fa1031d16e7) is directly related to this WSA Downloading fail bug, and [Pull request is still waiting for the approval](https://github.com/pagkly/MagiskOnWaydroid/pull/9#issue-1359944288) of this repo owner, you can feel free to fork from that repo, then again, the workflow will continue executing and stops at the next error, [which I also fixed by this commit](https://github.com/pagkly/MagiskOnWaydroid/pull/10/commits/25aebdcff0a478227a2b370dd8647925bb36c683)
[and also made the next pull request here](https://github.com/pagkly/MagiskOnWaydroid/pull/10#issue-1359945181)

Finally, Merged everything to master in my forked repo, and [I was able to generate the artifact here](https://github.com/BlurryFlurry/MagiskOnWaydroid/actions/runs/2978087525).
Feel free to fork from the master branch of my forked repo, and run the workflow, or wait for this repo owner's approval.
Cheerz
